import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import StyledComponentsRegistry from "@app/theme/registry.theme";
import StyledContext from "@app/contexts/styled";
import { BasketProvider } from "@app/contexts/basket";
import StoreProvider from "@app/state/redux-provider";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Waldo Contact Lenses",
  description: "Generated by Waldo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <StyledComponentsRegistry>
          <StyledContext>
            <StoreProvider>
              <BasketProvider>{children}</BasketProvider>
            </StoreProvider>
          </StyledContext>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
